{% set github_user_or_org = "drmpeg" %}
{% set github_repo = "gr-paint" %}
{% set version = "0.0.2021.10.22" %}
{% set oot_name = github_repo|replace("gr-", "") %}
{% set name = "gnuradio-" + oot_name %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ github_user_or_org }}/{{ github_repo }}/archive/9967e997b585060492c6837d180353254c1a1c47.tar.gz
  sha256: a11efd09d2d0cf8b6edbea1736a1f728505163559bc6224959240dfac033ba99

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - pkg-config

  host:
    - gmp  # [linux]
    - gnuradio-core
    - pip  # [win]
    - python
    - swig
    - volk

  run:
    - numpy
    - pillow
    - python

test:
  commands:
    # verify that (some) headers get installed
    - test -f $PREFIX/include/{{ oot_name }}/api.h  # [not win]
    - if not exist %PREFIX%\\Library\\include\\{{ oot_name }}\\api.h exit 1  # [win]

    # verify that libraries get installed
    - test -f $PREFIX/lib/lib{{ name }}${SHLIB_EXT}  # [not win]
    - if not exist %PREFIX%\\Library\\bin\\{{ name }}.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\{{ name }}.lib exit 1  # [win]

    # verify that (some) GRC blocks get installed
    {% set blocks = ["paint_image_source", "paint_paint_bc"] %}
    {% for block in blocks %}
    - test -f $PREFIX/share/gnuradio/grc/blocks/{{ block }}.block.yml  # [not win]
    - if not exist %PREFIX%\\Library\\share\\gnuradio\\grc\\blocks\\{{ block }}.block.yml exit 1  # [win]
    {% endfor %}

  imports:
    - {{ oot_name }}

about:
  home: https://github.com/{{ github_user_or_org }}/{{ github_repo }}
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: OFDM Spectrum Painter for GNU Radio
  description: >
    The goal of this project is to build a software-defined OFDM transmitter
    that "paints" monochrome images into the waterfall of a receiver.
    It is based on https://github.com/polygon/spectrum_painter

    After installation, a GNU Radio block called "Spectrum Painter" will
    be available in the "Paint" category. The block converts a byte stream
    of image data into a 4K IFFT OFDM IQ sequence for transmission.
  doc_url: https://github.com/{{ github_user_or_org }}/{{ github_repo }}
  dev_url: https://github.com/{{ github_user_or_org }}/{{ github_repo }}

extra:
  recipe-maintainers:
    - ryanvolz
